[package]
name = "chess-tui"
version = "0.1.3"
authors = ["Thomas Mauran"]
license = "MIT"
edition = "2021"
description = "A chess TUI implementation in rust ğŸ¦€"
keywords = ["tui", "graphics", "chess", "game", "board"]
homepage = "https://github.com/thomas-mauran/chess-tui"
repository = "https://github.com/thomas-mauran/chess-tui"

[dependencies]
crossterm = "0.26.1"
ratatui = "0.24.0"

[features]
chess-tui = []
default = ["chess-tui"]