[package]
name = "chess-tui"
version = "1.6.0"
authors = ["Thomas Mauran"]
license = "MIT"
edition = "2021"
description = "A rusty chess game in your terminal ðŸ¦€"
keywords = ["tui", "graphics", "chess", "game", "board"]
homepage = "https://github.com/thomas-mauran/chess-tui"
repository = "https://github.com/thomas-mauran/chess-tui"

[dependencies]
clap = { version = "4.4.11", features = ["derive"] }
dirs = "5.0.1"
ratatui = "0.28.1"
uci = "0.2.1"
toml = "0.5.8"
log = "0.4"
simplelog = "0.12"
chrono = "0.4"

[features]
chess-tui = []
default = ["chess-tui"]

[profile.release]
lto = true
codegen-units = 1
opt-level = "z"
strip = true
