[package]
name = "chess-tui"
version = "1.5.0"
authors = ["Thomas Mauran"]
license = "MIT"
edition = "2021"
description = "A rusty chess game in your terminal ðŸ¦€"
keywords = ["tui", "graphics", "chess", "game", "board"]
homepage = "https://github.com/thomas-mauran/chess-tui"
repository = "https://github.com/thomas-mauran/chess-tui"

[dependencies]
clap = { version = "4.4.11", features = ["derive"] }
dirs = "5.0.1"
ratatui = "0.28.1"
uci = "0.2.0"
toml = "0.5.8"
async-trait = "0.1.83"
tokio = { version = "1.41.1", features = ["full"] }
log = "0.4.22"
tokio-util = { version = "0.7.12", features = ["full"] } 
futures = "0.3.31"


[features]
chess-tui = []
default = ["chess-tui"]

[profile.release]
lto = true
codegen-units = 1
opt-level = "z"
strip = true
